### ISSUE TITLE
won't be able to execute xml2json even after successfully setting up the environment

### ISSUE THREAD

**Issue by weirditya** [knadh/xmlutils.py#49]
I built the environment successfully, and trying to run the command from directory xmlutils.py 
`xml2json --input "/sample/logs.xml" --output "/sample/logs.json"`

getting this error:

`Traceback (most recent call last):
  File "/home/xalteddev/anaconda3/bin/xml2json", line 33, in <module>
    sys.exit(load_entry_point('xmlutils==1.4.1', 'console_scripts', 'xml2json')())
  File "/home/xalteddev/anaconda3/lib/python3.8/site-packages/xmlutils/console.py", line 109, in run_xml2json
    parser.add_argument('--input', type=file, dest='input_file', required=True, help='input xml filename')
NameError: name 'file' is not defined`

**Comment by mia2wan** [comment]
I also have the same question as you, have your question been resolved?

**Comment by mia2wan** [comment]
I also have the same question as you, has your question been resolved?

**Comment by mia2wan** [comment]
> I built the environment successfully, and trying to run the command from directory xmlutils.py `xml2json --input "/sample/logs.xml" --output "/sample/logs.json"`
> 
> getting this error:
> 
> `Traceback (most recent call last): File "/home/xalteddev/anaconda3/bin/xml2json", line 33, in <module> sys.exit(load_entry_point('xmlutils==1.4.1', 'console_scripts', 'xml2json')()) File "/home/xalteddev/anaconda3/lib/python3.8/site-packages/xmlutils/console.py", line 109, in run_xml2json parser.add_argument('--input', type=file, dest='input_file', required=True, help='input xml filename') NameError: name 'file' is not defined`

I also have the same question as you, has your question been resolved?
